services:
  auth: 
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    ports: 
      - "3001:3001"
    env_file:
      - ./apps/auth/.env.local
    environment:
      NODE_ENV: development
      DB_HOST: host.docker.internal
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - rabbitmq
  orders: 
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
      # target: production
    command: yarn run start:dev orders
    # command: node dist/apps/orders/main
    ports: 
      - "3002:3002"
    env_file:
      - ./apps/orders/.env.local
    environment:
      NODE_ENV: development
      DB_HOST: host.docker.internal
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - rabbitmq
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports: 
      - "8081:80"
    volumes:
      - ./apps/api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - orders
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
volumes:
  auth_db_data:
  orders_db_data: