version: "3"
services:
  # database:
  #   image: "postgres:latest"
  #   ports:
  #     - ${POSTGRES_DEFAULT_PORT}:${POSTGRES_DEFAULT_PORT}
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
  #   volumes:
  #     - ./pg-data/:/var/lib/postgresql/data/
  test_database:
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password